export const C = {
  bg: "#0d0d0d",
  surface: "#161616",
  card: "#1c1c1c",
  sunken: "#111111",
  border: "#2a2a2a",
  text: "#f0f0f0",
  muted: "#7a7a7a",
  accent: "#39FF6A",
  accentDim: "#1a2a1f",
  danger: "#FF4D4D",
  dangerDim: "#2e0a0a",
  warn: "#FFB84D",
  hitBg: "#0a2e14",
  missBg: "#2e0a0a",
  font: "Inter, system-ui, -apple-system, sans-serif",
  mono: "'JetBrains Mono', 'Fira Mono', ui-monospace, monospace",
};

export const toneColor = (tone) =>
  tone === "hit" ? C.accent : tone === "miss" ? C.danger : tone === "ok" ? C.warn : C.muted;

export const S = {
  app: { minHeight: "100vh", background: C.bg, color: C.text },
  screen: { maxWidth: 520, margin: "0 auto", paddingBottom: 48 },

  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "14px 16px",
    background: C.surface,
    borderBottom: `1px solid ${C.border}`,
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  logo: { fontFamily: C.mono, fontWeight: 700, fontSize: 18, letterSpacing: 2 },
  headerTitle: {
    fontWeight: 600,
    fontSize: 15,
    flex: 1,
    textAlign: "center",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  section: { padding: "16px 16px 4px" },
  sectionLabel: {
    fontSize: 11,
    fontFamily: C.mono,
    letterSpacing: 2,
    color: C.muted,
    marginBottom: 10,
  },
  subLabel: {
    fontSize: 11,
    fontFamily: C.mono,
    letterSpacing: 2,
    color: C.muted,
    margin: "14px 0 6px",
  },

  card: {
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    padding: "14px 16px",
    marginBottom: 10,
  },
  cardRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 },
  cardTitle: { fontWeight: 600, fontSize: 16 },
  cardSub: { color: C.muted, fontSize: 12, marginTop: 2 },

  exCard: {
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    margin: "0 16px 8px",
    overflow: "hidden",
  },
  exHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    padding: "12px 14px",
    background: "none",
    border: "none",
    color: C.text,
    cursor: "pointer",
    width: "100%",
    textAlign: "left",
    font: "inherit",
  },
  exName: { fontWeight: 600, fontSize: 15 },
  exToggle: { color: C.muted, fontSize: 12 },
  exBody: { padding: "0 14px 14px" },

  setBlock: {
    background: C.sunken,
    borderRadius: 8,
    padding: "10px 12px",
    marginBottom: 8,
    borderLeft: `3px solid ${C.border}`,
  },
  setHead: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6, flexWrap: "wrap" },
  setRow: { display: "flex", gap: 12, alignItems: "flex-end", flexWrap: "wrap" },
  setInfo: { color: C.muted, fontSize: 12 },
  setBadge: {
    background: "#2a2a2a",
    color: C.accent,
    fontFamily: C.mono,
    fontSize: 11,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 4,
    letterSpacing: 1,
    whiteSpace: "nowrap",
  },
  repTarget: { marginLeft: "auto", fontFamily: C.mono, fontSize: 12, color: C.accent, fontWeight: 600 },

  prescribed: { display: "flex", alignItems: "baseline", gap: 8, marginBottom: 7, flexWrap: "wrap" },
  prescribedLabel: { color: C.muted, fontFamily: C.mono, fontSize: 11 },
  prescribedVal: { color: C.text, fontFamily: C.mono, fontSize: 12 },

  inputGroup: { display: "flex", flexDirection: "column", gap: 4 },
  inputLabel: { color: C.muted, fontSize: 11, letterSpacing: 0.5, fontFamily: C.mono },
  inputRow: { display: "flex", alignItems: "center", gap: 4 },
  unit: { color: C.muted, fontSize: 12, fontFamily: C.mono },

  wtInput: {
    background: "#222",
    border: `1px solid ${C.border}`,
    color: C.text,
    fontFamily: C.mono,
    fontSize: 16,
    padding: "8px 10px",
    borderRadius: 6,
    width: 78,
    textAlign: "right",
  },
  numInput: {
    background: "#222",
    border: `1px solid ${C.border}`,
    color: C.text,
    fontFamily: C.mono,
    fontSize: 16,
    padding: "8px 10px",
    borderRadius: 6,
    width: 64,
    textAlign: "right",
  },
  repsInput: {
    background: "#1a1a1a",
    border: `1px solid ${C.border}`,
    color: C.text,
    fontFamily: C.mono,
    fontSize: 16,
    padding: "8px 10px",
    borderRadius: 6,
    width: 64,
    textAlign: "center",
  },
  textInput: {
    background: "#222",
    border: `1px solid ${C.border}`,
    color: C.text,
    fontSize: 14,
    padding: "9px 10px",
    borderRadius: 6,
    width: "100%",
  },
  select: {
    background: "#222",
    border: `1px solid ${C.border}`,
    color: C.text,
    fontSize: 14,
    padding: "9px 10px",
    borderRadius: 6,
    width: "100%",
  },
  notes: {
    background: C.sunken,
    border: `1px solid ${C.border}`,
    color: C.text,
    fontSize: 13,
    padding: "9px 10px",
    borderRadius: 6,
    width: "100%",
    minHeight: 56,
    marginTop: 8,
    resize: "vertical",
  },
  dateInput: {
    background: "#222",
    border: `1px solid ${C.border}`,
    color: C.text,
    fontFamily: C.mono,
    fontSize: 14,
    padding: "8px 10px",
    borderRadius: 6,
  },

  btnPrimary: {
    background: C.accent,
    color: "#000",
    fontWeight: 700,
    fontSize: 13,
    padding: "10px 18px",
    borderRadius: 8,
    border: "none",
    cursor: "pointer",
  },
  btnGhost: {
    background: "none",
    color: C.text,
    fontSize: 13,
    padding: "10px 14px",
    borderRadius: 8,
    border: `1px solid ${C.border}`,
    cursor: "pointer",
  },
  btnSmall: {
    background: "none",
    color: C.muted,
    fontSize: 12,
    padding: "5px 10px",
    borderRadius: 6,
    border: `1px solid ${C.border}`,
    cursor: "pointer",
  },
  btnXs: {
    background: "#222",
    color: C.muted,
    fontSize: 11,
    padding: "4px 8px",
    borderRadius: 4,
    border: `1px solid ${C.border}`,
    cursor: "pointer",
  },
  btnAdd: {
    background: "none",
    color: C.accent,
    fontSize: 13,
    padding: "9px 0",
    border: "none",
    cursor: "pointer",
    fontFamily: C.mono,
    letterSpacing: 1,
    display: "block",
  },
  btnBack: {
    background: "none",
    color: C.muted,
    fontSize: 13,
    padding: "4px 0",
    border: "none",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  btnTemplate: {
    background: C.accentDim,
    color: C.accent,
    fontSize: 12,
    padding: "6px 10px",
    borderRadius: 6,
    border: "1px solid #2a4a2f",
    cursor: "pointer",
    fontFamily: C.mono,
  },
  btnToggle: {
    background: "#222",
    color: C.muted,
    fontSize: 10,
    padding: "2px 5px",
    borderRadius: 3,
    border: `1px solid ${C.border}`,
    cursor: "pointer",
    fontFamily: C.mono,
  },

  panel: { background: C.sunken, borderRadius: 8, padding: "10px 12px", marginBottom: 10 },
  note: {
    background: C.sunken,
    borderRadius: 6,
    padding: "7px 10px",
    fontSize: 12,
    color: C.muted,
    margin: "6px 0",
  },
  empty: { color: C.muted, textAlign: "center", padding: "48px 24px", fontSize: 13, lineHeight: 1.6 },

  table: { width: "100%", borderCollapse: "collapse", fontFamily: C.mono, fontSize: 12 },
  th: {
    textAlign: "right",
    color: C.muted,
    fontWeight: 400,
    padding: "2px 6px 5px",
    fontSize: 10,
    letterSpacing: 1,
    whiteSpace: "nowrap",
  },
  td: { textAlign: "right", padding: "6px", whiteSpace: "nowrap" },

  listItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    borderBottom: `1px solid ${C.border}`,
    color: C.text,
    padding: "14px 16px",
    cursor: "pointer",
    fontSize: 14,
    textAlign: "left",
    font: "inherit",
  },

  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.82)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: 24,
  },
  modal: {
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: 22,
    maxWidth: 360,
    width: "100%",
  },

  banner: (tone) => ({
    padding: "9px 12px",
    borderRadius: 6,
    fontSize: 13,
    marginTop: 10,
    background: tone === "error" ? C.dangerDim : C.hitBg,
    color: tone === "error" ? C.danger : C.accent,
    border: `1px solid ${tone === "error" ? C.danger : C.accent}`,
  }),
};
